spring.application.name=feed-api

spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=1234
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
logging.level.p6spy=DEBUG

mybatis.mapper-locations=classpath:mapper/**/*.xml